# Logistic Regression

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('data_task003.csv')

In [3]:
df.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years Department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [4]:
department_ = np.array(df['Department']).reshape(-1, 1)
ohe = OneHotEncoder(drop='first').fit(department_)
department_dummy = ohe.transform(department_).toarray()
department_df = pd.DataFrame(department_dummy, columns=ohe.categories_[0][1:])
department_df

RandD  accounting   hr  management  marketing  product_mng  sales  \
0        0.0         0.0  0.0         0.0        0.0          0.0    1.0   
1        0.0         0.0  0.0         0.0        0.0          0.0    1.0   
2        0.0         0.0  0.0         0.0        0.0          0.0    1.0   
3        0.0         0.0  0.0         0.0        0.0          0.0    1.0   
4        0.0         0.0  0.0         0.0        0.0          0.0    1.0   
...      ...         ...  ...         ...        ...          ...    ...   
14994    0.0         0.0  0.0         0.0        0.0          0.0    0.0   
14995    0.0         0.0  0.0         0.0        0.0          0.0    0.0   
14996    0.0         0.0  0.0         0.0        0.0          0.0    0.0   
14997    0.0         0.0  0.0         0.0        0.0          0.0    0.0   
14998    0.0         0.0  0.0         0.0        0.0          0.0    0.0   

       support  technical  
0          0.0        0.0  
1          0.0        0.0  
2          0.0        0.0  
3          0.0        0.0  
4          0.0        0.0  
...        ...        ...  
14994      1.0        0.0  
14995      1.0        0.0  
14996      1.0        0.0  
14997      1.0        0.0  
14998      1.0        0.0  

[14999 rows x 9 columns]

In [5]:
salaries = np.array(df['salary']).reshape(-1, 1)
ode = OrdinalEncoder(categories=[['low', 'medium', 'high']])
salaries = ode.fit_transform(salaries)
salary_df = pd.DataFrame(salaries, columns=['Salary'])

In [6]:
df = pd.concat([df.drop(['Department', 'salary'], axis=1), department_df, salary_df], axis=1)
df.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  RandD  \
0                   3              0     1                      0    0.0   
1                   6              0     1                      0    0.0   
2                   4              0     1                      0    0.0   
3                   5              0     1                      0    0.0   
4                   3              0     1                      0    0.0   

   accounting   hr  management  marketing  product_mng  sales  support  \
0         0.0  0.0         0.0        0.0          0.0    1.0      0.0   
1         0.0  0.0         0.0        0.0          0.0    1.0      0.0   
2         0.0  0.0         0.0        0.0          0.0    1.0      0.0   
3         0.0  0.0         0.0        0.0          0.0    1.0      0.0   
4         0.0  0.0         0.0        0.0          0.0    1.0      0.0   

   technical  Salary  
0        0.0     0.0  
1        0.0     1.0  
2        0.0     1.0  
3        0.0     0.0  
4        0.0     0.0

In [7]:
X = np.array(df.drop(['Salary'], axis=1))
y = np.array(df['Salary'])

In [8]:
X

array([[0.38, 0.53, 2.  , ..., 1.  , 0.  , 0.  ],
       [0.8 , 0.86, 5.  , ..., 1.  , 0.  , 0.  ],
       [0.11, 0.88, 7.  , ..., 1.  , 0.  , 0.  ],
       ...,
       [0.37, 0.53, 2.  , ..., 0.  , 1.  , 0.  ],
       [0.11, 0.96, 6.  , ..., 0.  , 1.  , 0.  ],
       [0.37, 0.52, 2.  , ..., 0.  , 1.  , 0.  ]])

In [9]:
y

array([0., 1., 1., ..., 0., 0., 0.])

In [10]:
scalar = StandardScaler().fit(X)
X = scalar.transform(X)

In [11]:
x_train, x_test, y_train, y_test = train_test_split(X, y, train_size=0.8, shuffle=True)
logistic_reg = LogisticRegression().fit(x_train, y_train)
logistic_reg.score(x_test, y_test)

0.5186666666666667

In [12]:
logistic_reg.coef_

array([[ 1.00648540e-02,  3.95364508e-02,  1.41857859e-02,
        -1.71846419e-02, -8.01589857e-02,  3.37364777e-02,
         3.33933374e-01, -1.04603686e-01,  3.29945425e-03,
        -3.60876295e-02, -2.78239815e-02, -1.52179106e-01,
        -2.08960036e-02, -1.55282184e-03,  3.42994063e-02,
         3.33614905e-03, -8.22085782e-03],
       [ 1.69860803e-02,  2.53554325e-02,  7.45172914e-03,
         3.93635866e-04,  8.04176415e-03, -1.80613356e-03,
         1.15824044e-01,  3.87492846e-02,  2.44361061e-02,
        -1.97766818e-02,  2.30292134e-02, -9.81224208e-02,
        -2.76227515e-02, -1.43086447e-02, -8.95833187e-03,
        -5.56757543e-03, -2.57767125e-02],
       [-2.70509343e-02, -6.48918833e-02, -2.16375151e-02,
         1.67910060e-02,  7.21172215e-02, -3.19303442e-02,
        -4.49757418e-01,  6.58544009e-02, -2.77355603e-02,
         5.58643113e-02,  4.79476807e-03,  2.50301526e-01,
         4.85187551e-02,  1.58614665e-02, -2.53410744e-02,
         2.23142638e-03,  3.3