# Logistic Regression

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('data_task003.csv')

In [3]:
df.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years Department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [4]:
department_ = np.array(df['Department']).reshape(-1, 1)
ohe = OneHotEncoder(drop='first').fit(department_)
department_dummy = ohe.transform(department_).toarray()
department_df = pd.DataFrame(department_dummy, columns=ohe.categories_[0][1:])
department_df

RandD  accounting   hr  management  marketing  product_mng  sales  \
0        0.0         0.0  0.0         0.0        0.0          0.0    1.0   
1        0.0         0.0  0.0         0.0        0.0          0.0    1.0   
2        0.0         0.0  0.0         0.0        0.0          0.0    1.0   
3        0.0         0.0  0.0         0.0        0.0          0.0    1.0   
4        0.0         0.0  0.0         0.0        0.0          0.0    1.0   
...      ...         ...  ...         ...        ...          ...    ...   
14994    0.0         0.0  0.0         0.0        0.0          0.0    0.0   
14995    0.0         0.0  0.0         0.0        0.0          0.0    0.0   
14996    0.0         0.0  0.0         0.0        0.0          0.0    0.0   
14997    0.0         0.0  0.0         0.0        0.0          0.0    0.0   
14998    0.0         0.0  0.0         0.0        0.0          0.0    0.0   

       support  technical  
0          0.0        0.0  
1          0.0        0.0  
2          0.0        0.0  
3          0.0        0.0  
4          0.0        0.0  
...        ...        ...  
14994      1.0        0.0  
14995      1.0        0.0  
14996      1.0        0.0  
14997      1.0        0.0  
14998      1.0        0.0  

[14999 rows x 9 columns]

In [5]:
salaries = np.array(df['salary']).reshape(-1, 1)
ode = OrdinalEncoder(categories=[['low', 'medium', 'high']])
salaries = ode.fit_transform(salaries)
salary_df = pd.DataFrame(salaries, columns=['Salary'])

In [6]:
df = pd.concat([df.drop(['Department', 'salary'], axis=1), department_df, salary_df], axis=1)
df.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  RandD  \
0                   3              0     1                      0    0.0   
1                   6              0     1                      0    0.0   
2                   4              0     1                      0    0.0   
3                   5              0     1                      0    0.0   
4                   3              0     1                      0    0.0   

   accounting   hr  management  marketing  product_mng  sales  support  \
0         0.0  0.0         0.0        0.0          0.0    1.0      0.0   
1         0.0  0.0         0.0        0.0          0.0    1.0      0.0   
2         0.0  0.0         0.0        0.0          0.0    1.0      0.0   
3         0.0  0.0         0.0        0.0          0.0    1.0      0.0   
4         0.0  0.0         0.0        0.0          0.0    1.0      0.0   

   technical  Salary  
0        0.0     0.0  
1        0.0     1.0  
2        0.0     1.0  
3        0.0     0.0  
4        0.0     0.0

In [7]:
X = np.array(df.drop(['Salary'], axis=1))
y = np.array(df['Salary'])

In [8]:
X

array([[0.38, 0.53, 2.  , ..., 1.  , 0.  , 0.  ],
       [0.8 , 0.86, 5.  , ..., 1.  , 0.  , 0.  ],
       [0.11, 0.88, 7.  , ..., 1.  , 0.  , 0.  ],
       ...,
       [0.37, 0.53, 2.  , ..., 0.  , 1.  , 0.  ],
       [0.11, 0.96, 6.  , ..., 0.  , 1.  , 0.  ],
       [0.37, 0.52, 2.  , ..., 0.  , 1.  , 0.  ]])

In [9]:
y

array([0., 1., 1., ..., 0., 0., 0.])

In [10]:
scalar = StandardScaler().fit(X)
X = scalar.transform(X)

In [11]:
x_train, x_test, y_train, y_test = train_test_split(X, y, train_size=0.8, shuffle=True)
logistic_reg = LogisticRegression().fit(x_train, y_train)
logistic_reg.score(x_test, y_test)

0.51

In [12]:
logistic_reg.coef_

array([[ 0.01738914,  0.04188934,  0.01860469, -0.02624732, -0.07233942,
         0.03461969,  0.33867111, -0.10558493,  0.00216645, -0.04054128,
        -0.02049249, -0.16043964, -0.0388051 , -0.01124528,  0.00886016,
         0.01115551, -0.01565952],
       [ 0.0213305 ,  0.02290078,  0.01411391,  0.00668219,  0.02518071,
        -0.00050768,  0.12181506,  0.03606974,  0.02183743, -0.02012717,
         0.03333667, -0.09559504, -0.0231638 , -0.01023887,  0.00601673,
        -0.00267908, -0.02448932],
       [-0.03871964, -0.06479012, -0.0327186 ,  0.01956513,  0.0471587 ,
        -0.03411201, -0.46048616,  0.06951519, -0.02400388,  0.06066845,
        -0.01284418,  0.25603469,  0.0619689 ,  0.02148415, -0.01487689,
        -0.00847643,  0.04014884]])

In [14]:
prediction_result = logistic_reg.predict(x_test)

In [32]:
x_test = scalar.inverse_transform(x_test)

In [37]:
result_df = pd.DataFrame(x_test[:, 0:8], columns=df.columns[0:8])
result_df.head(5)

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.91             1.00             4.0                 251.0   
1                0.15             0.75             3.0                 259.0   
2                0.62             0.77             3.0                 204.0   
3                0.42             0.44             3.0                 183.0   
4                0.59             0.71             5.0                 222.0   

   time_spend_company  Work_accident          left  promotion_last_5years  
0                 6.0            0.0  1.000000e+00                    0.0  
1                 8.0            1.0 -2.775558e-17                    0.0  
2                 4.0            0.0 -2.775558e-17                    0.0  
3                 2.0            0.0 -2.775558e-17                    0.0  
4                 3.0            0.0 -2.775558e-17                    0.0

In [40]:
result_department = ohe.inverse_transform(x_test[:, 8:17])
result_salary = ode.inverse_transform(prediction_result.reshape(-1, 1))

In [52]:
result_df['Department'] = pd.Series(result_department.reshape(-1,))
result_df['Salary'] = pd.Series(result_salary.reshape(-1,))
result_df['left'] = result_df['left'].apply(lambda x: 0 if x < 0.5 else 1)
result_df['promotion_last_5years'] = result_df['promotion_last_5years'].apply(lambda x: 0 if x < 0.5 else 1)
result_df.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.91             1.00             4.0                 251.0   
1                0.15             0.75             3.0                 259.0   
2                0.62             0.77             3.0                 204.0   
3                0.42             0.44             3.0                 183.0   
4                0.59             0.71             5.0                 222.0   

   time_spend_company  Work_accident  left  promotion_last_5years  \
0                 6.0            0.0     1                      0   
1                 8.0            1.0     0                      0   
2                 4.0            0.0     0                      0   
3                 2.0            0.0     0                      0   
4                 3.0            0.0     0                      0   

    Department  Salary  
0    technical     low  
1    marketing  medium  
2        sales     low  
3  product_mng     low  
4    technical     low

In [58]:
result_df.to_csv('Logistic_reg.csv', index=False)